### ISSUE TITLE
HID monitor not working

### ISSUE THREAD

**Issue by vinmred** [changeofpace/MouHidInputHook#3]
I compiled the MouHIDinputhook in visual studio and tried running the application. There is a command prompt that shows up for an instant then closes out. Any idea what is happening? I am using windows 10 and visual studio 2019.

**Comment by changeofpace** [comment]
Follow these steps then paste the command prompt output / DbgView output.

1. Enable test mode on the target machine.
2. Start DbgView. Click Capture menu entry. Enable all options.
3. Load the driver using a driver loader program (e.g., https://github.com/tandasat/DrvLoader)
4. Open command prompt and run the application.
